### PR TITLE
fix: record last version after recovery

### LINKED ISSUE #30: Event recovery does not record last_version correctly
Instead it always sets the `last_version` field to None in https://github.com/hseeberger/evented/blob/9d62331e27321ba23998ebe9f265a459e77d8ab8/src/entity.rs#L147 so that when an entity is reinstantiated it will fail after handling the next command in https://github.com/hseeberger/evented/blob/9d62331e27321ba23998ebe9f265a459e77d8ab8/src/entity.rs#L318

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #30

### CODE REVIEW

File: src/entity.rs [hunk 1]
```diff
@@ -134,17 +134,17 @@ where
     /// Build the [EventSourcedEntity] by loading and applying the current events.
     pub async fn build(self, id: E::Id, pool: Pool) -> Result<EventSourcedEntity<E, L>, Error> {
         let events = current_events_by_id::<E>(&id, &pool).await;
-        let entity = events
-            .try_fold(self.entity, |mut state, (_, event)| {
+        let (version, entity) = events
+            .try_fold((0u64, self.entity), |(_, mut state), (version, event)| {
```
Comment (hseeberger) [inline src/entity.rs:138]: Could we start with `None` here and not use `get` below, i.e. work with the `Option<NonZeroU...>`? And use the identifier `last_version`? Then line 147 could be simply rewritten as `last_version`.

**Review by hseeberger — CHANGES_REQUESTED** [review]
Thanks a lot for spotting and fixing this.

File: src/entity.rs (hunk 1 above)
Comment (jrudolph) [reply src/entity.rs]: True, much simpler.

**Review by hseeberger — APPROVED** [review]
